### ISSUE TITLE
IndexError in POST /reply 

### ISSUE THREAD

**Issue by makupi** [jrabbit/pyborg-1up#117]
I'm running mod_discord together with mod_http and I'm regularly getting an IndexError on /reply posts. 
Traceback:
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\bottle.py", line 868, in _handle
    return route.call(**args)
  File "C:\Python38\lib\site-packages\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "C:\Python38\lib\site-packages\pyborg\util\bottle_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\pyborg\mod\mod_http.py", line 46, in reply
    return pyborg.reply(body)
  File "C:\Python38\lib\site-packages\pyborg\pyborg.py", line 1112, in reply
    if cwords[w] != word:
IndexError: list index out of range
127.0.0.1 - - [12/Apr/2020 04:38:54] "POST /reply HTTP/1.1" 500 746
```

**Comment by jrabbit** [comment]
I'm going to suspect there's a windows problem w/ the circa 2002 code. Can you get more debug output with `pyborg --debug http ...` (iirc, check help output if thats wrong)

**Comment by makupi** [comment]
```
DEBUG:pyborg.pyborg:{'body': '#nick you alive?', '_words': ['#nick', 'you', 'alive?'], 'words': ['#nick', 'you', 'alive?'], 'i': 'alive?', 'index': ['#nick'], 'known': 84, 'known_min': 3, 'w': 1, 'k': 1, '_mappable_nick_clean': <function pyborg.reply.<locals>._mappable_nick_clean at 0x7f9e5f185510>, 'tokenized': ['#nick', 'you', 'alive', '?'], 'tagged': [('#nick', 'NN'), ('you', 'PRP'), ('alive', 'VBP'), ('?', '.')], 'weighted_choices': [('#nick', 1), ('you', 2), ('alive', 2), ('?', 2)], 'population': ['#nick', 'you', 'you', 'alive', 'alive', '?', '?'], 'word': 'nick', 'counter': 0, 'done': 0, 'pre_words': {'': 0}, 'x': 8, 'sentence': ['nick', 'fuck', 'you'], 'weight': <function pyborg.reply.<locals>.weight at 0x7f9e5f185488>, 'l': 1954655749, 'context': '#nick stop lying #nick', 'num_context': 1, 'cwords': ['#nick', 'stop', 'lying', '#nick'], 'look_for': 'no', 'liste': [('#nick', 1), ('fuck', 1), ('no', 1), ('dumb', 2), ('nick', 2), ('', 7)], 'numbers': [1, 2, 3, 5, 7, 14], 'mot': ['nick'], 'self': I am a version 2.0.0 Pyborg with 984 words and 616 lines. With a settings of: FakeCfg2(aliases={}, num_aliases=0, ignore_list=[], max_words=50000, num_words=984, num_contexts=3783, no_save=False, learning=True)}
DEBUG:pyborg.pyborg:trying to unpack: {'hashval': 1954655749, 'index': 5}
Traceback (most recent call last):
  File "/home/maku/.local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/maku/.local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/maku/.local/lib/python3.7/site-packages/pyborg/util/bottle_plugin.py", line 39, in wrapper
    return callback(*args, **kwargs)
  File "/home/maku/.local/lib/python3.7/site-packages/pyborg/mod/mod_http.py", line 46, in reply
    return pyborg.reply(body)
  File "/home/maku/.local/lib/python3.7/site-packages/pyborg/pyborg.py", line 1112, in reply
    if cwords[w] != word:
IndexError: list index out of range
127.0.0.1 - - [13/Apr/2020 16:36:43] "POST /reply HTTP/1.1" 500 746
```
